"""initial

Revision ID: 1474a714bc0b
Revises:
Create Date: 2026-04-08 12:09:25.546242

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1474a714bc0b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artists")),
    )
    op.create_table(
        "currencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_currencies")),
    )
    op.create_table(
        "grades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grades")),
    )
    op.create_table(
        "links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_links")),
    )
    op.create_table(
        "materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
        sa.UniqueConstraint("name", name=op.f("uq_materials_name")),
    )
    op.create_table(
        "shops",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shops")),
        sa.UniqueConstraint("name", name=op.f("uq_shops_name")),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["tags.id"], name=op.f("fk_tags_parent_id_tags")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("name", name=op.f("uq_tags_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "artists_links",
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("link_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
            name=op.f("fk_artists_links_artist_id_artists"),
        ),
        sa.ForeignKeyConstraint(
            ["link_id"], ["links.id"], name=op.f("fk_artists_links_link_id_links")
        ),
        sa.PrimaryKeyConstraint("artist_id", "link_id", name=op.f("pk_artists_links")),
    )
    op.create_table(
        "pin_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_pin_sets_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pin_sets")),
    )
    op.create_table(
        "pins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "acquisition_type",
            sa.Enum("single", "blind_box", "set", name="acquisitiontype"),
            nullable=False,
        ),
        sa.Column("front_image_guid", sa.Uuid(), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("limited_edition", sa.Boolean(), nullable=True),
        sa.Column("number_produced", sa.Integer(), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "funding_type",
            sa.Enum("self", "crowdfunded", "sponsored", name="fundingtype"),
            nullable=True,
        ),
        sa.Column("posts", sa.Integer(), nullable=False),
        sa.Column("width", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("back_image_guid", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("sku", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.id"],
            name=op.f("fk_pins_currency_id_currencies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pins")),
    )
    op.create_table(
        "shops_links",
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("link_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["link_id"], ["links.id"], name=op.f("fk_shops_links_link_id_links")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_shops_links_shop_id_shops")
        ),
        sa.PrimaryKeyConstraint("shop_id", "link_id", name=op.f("pk_shops_links")),
    )
    op.create_table(
        "user_auth_providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "provider", sa.Enum("google", "discord", native_enum=False), nullable=False
        ),
        sa.Column("provider_user_id", sa.String(), nullable=False),
        sa.Column("provider_email", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_auth_providers_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_auth_providers")),
        sa.UniqueConstraint(
            "provider", "provider_user_id", name=op.f("uq_user_auth_providers_provider")
        ),
    )
    op.create_table(
        "user_sessions",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_user_sessions")),
    )
    op.create_table(
        "pin_set_memberships",
        sa.Column("pin_id", sa.Integer(), nullable=False),
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["pin_id"], ["pins.id"], name=op.f("fk_pin_set_memberships_pin_id_pins")
        ),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["pin_sets.id"],
            name=op.f("fk_pin_set_memberships_set_id_pin_sets"),
        ),
        sa.PrimaryKeyConstraint(
            "pin_id", "set_id", name=op.f("pk_pin_set_memberships")
        ),
    )
    op.create_table(
        "pin_sets_links",
        sa.Column("pin_set_id", sa.Integer(), nullable=False),
        sa.Column("link_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["link_id"], ["links.id"], name=op.f("fk_pin_sets_links_link_id_links")
        ),
        sa.ForeignKeyConstraint(
            ["pin_set_id"],
            ["pin_sets.id"],
            name=op.f("fk_pin_sets_links_pin_set_id_pin_sets"),
        ),
        sa.PrimaryKeyConstraint(
            "pin_set_id", "link_id", name=op.f("pk_pin_sets_links")
        ),
    )
    op.create_table(
        "pins_artists",
        sa.Column("pin_id", sa.Integer(), nullable=False),
        sa.Column("artists_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artists_id"],
            ["artists.id"],
            name=op.f("fk_pins_artists_artists_id_artists"),
        ),
        sa.ForeignKeyConstraint(
            ["pin_id"], ["pins.id"], name=op.f("fk_pins_artists_pin_id_pins")
        ),
        sa.PrimaryKeyConstraint("pin_id", "artists_id", name=op.f("pk_pins_artists")),
    )
    op.create_table(
        "pins_grades",
        sa.Column("pin_id", sa.Integer(), nullable=False),
        sa.Column("grade_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grade_id"], ["grades.id"], name=op.f("fk_pins_grades_grade_id_grades")
        ),
        sa.ForeignKeyConstraint(
            ["pin_id"], ["pins.id"], name=op.f("fk_pins_grades_pin_id_pins")
        ),
        sa.PrimaryKeyConstraint("pin_id", "grade_id", name=op.f("pk_pins_grades")),
    )
    op.create_table(
        "pins_links",
        sa.Column("pin_id", sa.Integer(), nullable=False),
        sa.Column("link_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["link_id"], ["links.id"], name=op.f("fk_pins_links_link_id_links")
        ),
        sa.ForeignKeyConstraint(
            ["pin_id"], ["pins.id"], name=op.f("fk_pins_links_pin_id_pins")
        ),
        sa.PrimaryKeyConstraint("pin_id", "link_id", name=op.f("pk_pins_links")),
    )
    op.create_table(
        "pins_materials",
        sa.Column("pin_id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_pins_materials_material_id_materials"),
        ),
        sa.ForeignKeyConstraint(
            ["pin_id"], ["pins.id"], name=op.f("fk_pins_materials_pin_id_pins")
        ),
        sa.PrimaryKeyConstraint(
            "pin_id", "material_id", name=op.f("pk_pins_materials")
        ),
    )
    op.create_table(
        "pins_shops",
        sa.Column("pin_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pin_id"], ["pins.id"], name=op.f("fk_pins_shops_pin_id_pins")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_pins_shops_shop_id_shops")
        ),
        sa.PrimaryKeyConstraint("pin_id", "shop_id", name=op.f("pk_pins_shops")),
    )
    op.create_table(
        "pins_tags",
        sa.Column("pin_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pin_id"], ["pins.id"], name=op.f("fk_pins_tags_pin_id_pins")
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_pins_tags_tag_id_tags")
        ),
        sa.PrimaryKeyConstraint("pin_id", "tag_id", name=op.f("pk_pins_tags")),
    )
    op.create_table(
        "user_favorite_pin_sets",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("pin_set_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pin_set_id"],
            ["pin_sets.id"],
            name=op.f("fk_user_favorite_pin_sets_pin_set_id_pin_sets"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_favorite_pin_sets_user_id_users"),
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "pin_set_id", name=op.f("pk_user_favorite_pin_sets")
        ),
    )
    op.create_table(
        "user_favorite_pins",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("pin_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pin_id"], ["pins.id"], name=op.f("fk_user_favorite_pins_pin_id_pins")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_favorite_pins_user_id_users")
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "pin_id", name=op.f("pk_user_favorite_pins")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_favorite_pins")
    op.drop_table("user_favorite_pin_sets")
    op.drop_table("pins_tags")
    op.drop_table("pins_shops")
    op.drop_table("pins_materials")
    op.drop_table("pins_links")
    op.drop_table("pins_grades")
    op.drop_table("pins_artists")
    op.drop_table("pin_sets_links")
    op.drop_table("pin_set_memberships")
    op.drop_table("user_sessions")
    op.drop_table("user_auth_providers")
    op.drop_table("shops_links")
    op.drop_table("pins")
    op.drop_table("pin_sets")
    op.drop_table("artists_links")
    op.drop_table("users")
    op.drop_table("tags")
    op.drop_table("shops")
    op.drop_table("materials")
    op.drop_table("links")
    op.drop_table("grades")
    op.drop_table("currencies")
    op.drop_table("artists")
    # ### end Alembic commands ###
