"""add_user_collection_tables

Revision ID: dd2ee36584ee
Revises: 1474a714bc0b
Create Date: 2026-04-09 23:36:50.469983

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd2ee36584ee"
down_revision: Union[str, Sequence[str], None] = "1474a714bc0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_owned_pins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("pin_id", sa.Integer(), nullable=False),
        sa.Column("grade_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("tradeable_quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grade_id"], ["grades.id"], name=op.f("fk_user_owned_pins_grade_id_grades")
        ),
        sa.ForeignKeyConstraint(
            ["pin_id"], ["pins.id"], name=op.f("fk_user_owned_pins_pin_id_pins")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_owned_pins_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_owned_pins")),
        sa.UniqueConstraint(
            "user_id",
            "pin_id",
            "grade_id",
            name=op.f("uq_user_owned_pins_user_id"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "user_wanted_pins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("pin_id", sa.Integer(), nullable=False),
        sa.Column("grade_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["grade_id"],
            ["grades.id"],
            name=op.f("fk_user_wanted_pins_grade_id_grades"),
        ),
        sa.ForeignKeyConstraint(
            ["pin_id"], ["pins.id"], name=op.f("fk_user_wanted_pins_pin_id_pins")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_wanted_pins_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_wanted_pins")),
        sa.UniqueConstraint(
            "user_id",
            "pin_id",
            "grade_id",
            name=op.f("uq_user_wanted_pins_user_id"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_wanted_pins")
    op.drop_table("user_owned_pins")
    # ### end Alembic commands ###
