"""add user displays and content reports

Purely additive: four new tables, no ALTER on anything that exists, no PG enum
types (the enum columns are ``native_enum=False`` VARCHARs). A container running
the previous release never touches any of it, so this is safe to apply during the
blue/green overlap.

Revision ID: fc8470c7fd18
Revises: a7f3c21e9b04
Create Date: 2026-07-12 17:00:28.915305

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc8470c7fd18"
down_revision: Union[str, Sequence[str], None] = "a7f3c21e9b04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum(
                "display_image",
                "pin",
                "tag",
                "shop",
                "artist",
                "pin_set",
                "user",
                name="reporttargettype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("reporter_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "dismissed",
                "actioned",
                name="reportstatus",
                native_enum=False,
                length=32,
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_by_id", sa.Integer(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
            name=op.f("fk_content_reports_reporter_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"],
            ["users.id"],
            name=op.f("fk_content_reports_resolved_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_reports")),
        sa.UniqueConstraint(
            "reporter_id",
            "target_type",
            "target_id",
            name="uq_content_reports_reporter_target",
        ),
    )
    op.create_index(
        "ix_content_reports_status_created_at",
        "content_reports",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_content_reports_target",
        "content_reports",
        ["target_type", "target_id"],
        unique=False,
    )
    op.create_table(
        "user_displays",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("blurb", sa.Text(), nullable=True),
        sa.Column(
            "layout",
            sa.Enum(
                "collage",
                "grid",
                "vertical",
                "carousel",
                name="displaylayout",
                native_enum=False,
                length=32,
            ),
            server_default="collage",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_user_displays_created_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_id"],
            ["users.id"],
            name=op.f("fk_user_displays_deleted_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_user_displays_updated_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_displays_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_displays")),
        sa.UniqueConstraint("user_id", name="uq_user_displays_user_id"),
    )
    op.create_table(
        "user_display_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_id", sa.Integer(), nullable=False),
        sa.Column("image_guid", sa.Uuid(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "size_hint",
            sa.Enum(
                "normal",
                "feature",
                name="displayimagesize",
                native_enum=False,
                length=32,
            ),
            server_default="normal",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_user_display_images_created_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_id"],
            ["users.id"],
            name=op.f("fk_user_display_images_deleted_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["display_id"],
            ["user_displays.id"],
            name=op.f("fk_user_display_images_display_id_user_displays"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_user_display_images_updated_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_display_images")),
    )
    op.create_index(
        "ix_user_display_images_display_id_position",
        "user_display_images",
        ["display_id", "position"],
        unique=False,
    )
    op.create_table(
        "display_image_pins",
        sa.Column("display_image_id", sa.Integer(), nullable=False),
        sa.Column("pin_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["display_image_id"],
            ["user_display_images.id"],
            name=op.f("fk_display_image_pins_display_image_id_user_display_images"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pin_id"], ["pins.id"], name=op.f("fk_display_image_pins_pin_id_pins")
        ),
        sa.PrimaryKeyConstraint(
            "display_image_id", "pin_id", name=op.f("pk_display_image_pins")
        ),
    )
    op.create_index(
        "ix_display_image_pins_pin_id", "display_image_pins", ["pin_id"], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_display_image_pins_pin_id", table_name="display_image_pins")
    op.drop_table("display_image_pins")
    op.drop_index(
        "ix_user_display_images_display_id_position", table_name="user_display_images"
    )
    op.drop_table("user_display_images")
    op.drop_table("user_displays")
    op.drop_index("ix_content_reports_target", table_name="content_reports")
    op.drop_index("ix_content_reports_status_created_at", table_name="content_reports")
    op.drop_table("content_reports")
    # ### end Alembic commands ###
