#!/usr/bin/env node
/**
 * Scan the PinDB source for Lucide icon names, then bundle a tree-shaken
 * `lucide` global via Rolldown (subset of the full UMD `lucide.min.js`).
 */
import { readFile, readdir, writeFile, mkdir, stat } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "rolldown";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "../..");
const VENDOR = join(ROOT, "src/pindb/static/vendor");
const CACHE = join(__dirname, ".cache");
const OUT_FILE = join(VENDOR, "lucide.min.js");
const SCAN_ROOTS = [join(ROOT, "src/pindb")];

/**
 * Hand-maintained: dynamic / API icons the regex will not list as literals.
 */
const EXTRA_KEBAB = new Set([
  "tag",
  "copyright",
  "user",
  "paw-print",
  "info",
  "gem",
  "paint-bucket",
]);

function toCamelCase(string) {
  return string.replace(
    /^([A-Z])|[\s-_]+(\w)/g,
    (match, p1, p2) => (p2 ? p2.toUpperCase() : p1.toLowerCase())
  );
}

function toPascalCase(string) {
  const c = toCamelCase(string);
  return c.charAt(0).toUpperCase() + c.slice(1);
}

const RE_DATA_LUCIDE = /data_lucide=(['"])([a-z0-9][a-z0-9-]*)\1/g;
const RE_DATA_LUCIDE_DASH = /data-lucide=(['"])([a-z0-9][a-z0-9-]*)\1/g;
const RE_ICON_STR = /(?:^|[^a-z0-9_])icon=(['"])([a-z0-9][a-z0-9-]*)\1/g;
const RE_DATA_ICON = /data_icon=(['"])([a-z0-9][a-z0-9-]*)\1/g;

/**
 * @param {string} path
 * @param {(name: string) => void} onIcon
 */
async function walkAndCollect(path, onIcon) {
  const entries = await readdir(path, { withFileTypes: true });
  for (const ent of entries) {
    const p = join(path, ent.name);
    if (ent.isDirectory()) {
      if (ent.name === "__pycache__" || ent.name === "static") {
        continue;
      }
      await walkAndCollect(p, onIcon);
    } else if (ent.isFile() && (ent.name.endsWith(".py") || ent.name.endsWith(".js"))) {
      const text = await readFile(p, "utf8");
      for (const re of [RE_DATA_LUCIDE, RE_DATA_LUCIDE_DASH, RE_DATA_ICON]) {
        re.lastIndex = 0;
        let m;
        while ((m = re.exec(text)) != null) {
          onIcon(m[2], p);
        }
      }
      RE_ICON_STR.lastIndex = 0;
      let m;
      while ((m = RE_ICON_STR.exec(text)) != null) {
        onIcon(m[2], p);
      }
    }
  }
}

async function parseTagBranding(icons) {
  const p = join(ROOT, "src", "pindb", "templates", "components", "tag_branding.py");
  try {
    const text = await readFile(p, "utf8");
    const re = /TagCategory\.\s*\w+:\s*"([a-z0-9-]+)"/g;
    let m;
    while ((m = re.exec(text)) != null) {
      icons.add(m[1]);
    }
  } catch {
    /* ok */
  }
}

function isAcceptableKebab(t) {
  if (t.length < 2) {
    return false;
  }
  if (/^\d+$/.test(t)) {
    return false;
  }
  return true;
}

async function collectKebabSet() {
  const icons = new Set();
  for (const k of EXTRA_KEBAB) {
    icons.add(k);
  }
  for (const root of SCAN_ROOTS) {
    await walkAndCollect(
      root,
      (raw) => {
        if (typeof raw !== "string") {
          return;
        }
        const t = raw.trim();
        if (!isAcceptableKebab(t)) {
          return;
        }
        icons.add(t);
      }
    );
  }
  await parseTagBranding(icons);
  return icons;
}

/**
 * @param {Record<string, unknown>} mod
 * @param {string} pascal
 */
function getLucideKey(mod, pascal) {
  if (pascal[0] !== pascal[0].toUpperCase()) {
    return null;
  }
  if (Object.prototype.hasOwnProperty.call(mod, pascal) && mod[pascal]) {
    return pascal;
  }
  return null;
}

/**
 * @param {string[]} sortedKebabs
 * @param {string[]} uniquePascals (sorted)
 */
function buildEntryCode(sortedKebabs, uniquePascals) {
  const im = ["createIcons", ...uniquePascals].sort();
  const ob = uniquePascals.map((p) => `  ${p},`).join("\n");
  return `// Generated by scripts/lucide/build-lucide.mjs — do not edit.
// ${sortedKebabs.length} data-lucide / icon= uses → ${
    uniquePascals.length
  } unique ESM icon exports.
// Kebabs: ${sortedKebabs.join(", ")}
import { ${im.join(", ")} } from "lucide";

const iconAndAliases = {
${ob}
};

function pindbCreateIcons(opts) {
  if (opts == null) {
    return createIcons({ icons: iconAndAliases, root: document });
  }
  const o = { ...opts };
  let root = o.root;
  if (root == null && o.nodes && o.nodes[0]) {
    root = o.nodes[0];
  }
  if (root == null) {
    root = document;
  }
  const { nodes, ...rest } = o;
  return createIcons({
    ...rest,
    root,
    icons: o.icons != null ? o.icons : iconAndAliases,
  });
}

const lucide = {
  createIcons: pindbCreateIcons,
  icons: iconAndAliases
};

export default lucide;
`;
}

async function main() {
  const kebabSet = await collectKebabSet();
  const mod = await import("lucide");

  /** Component name (Pascal) → true */
  const pascalUsed = new Map();

  for (const k of kebabSet) {
    const p = toPascalCase(k);
    const key = getLucideKey(mod, p);
    if (!key) {
      console.error(
        `lucide build: no named export in lucide for name "${k}" (expected \`${p}\`).`
      );
      process.exit(1);
    }
    pascalUsed.set(key, true);
  }

  const uniquePascals = [...pascalUsed.keys()].sort();
  const sortedKeb = [...kebabSet].sort();
  const entry = buildEntryCode(sortedKeb, uniquePascals);

  await mkdir(VENDOR, { recursive: true });
  await mkdir(CACHE, { recursive: true });
  const entryPath = join(CACHE, "lucide-entry.mjs");
  await writeFile(entryPath, entry, "utf8");

  await build({
    input: entryPath,
    output: {
      file: OUT_FILE,
      format: "iife",
      name: "lucide",
      minify: true,
      sourcemap: false,
    },
    logLevel: "warn",
  });

  const s = await stat(OUT_FILE);
  const kb = (s.size / 1024).toFixed(1);
  console.log(
    `lucide: ${uniquePascals.length} ESM icon exports, ${[...kebabSet].length} data-lucide / icon= names -> static/vendor/lucide.min.js (${kb} kb)`
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
